# Generated by Django 3.2.25 on 2024-11-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_designrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='admin_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_photos/'),
        ),
    ]
